/** @type {import('tailwindcss').Config} */
module.exports = {
  mode: 'jit',
  purge: [
    './src/**/*.{js,jsx,ts,tsx,md}',
    './safelist.txt',
  ],
  theme: {
    extend: {},
  },
  plugins: [
    require('tailwind-safelist-generator')({
      path: 'safelist.txt',
      // https://tailwindcss.com/docs/theme#configuration-reference
      patterns: [
        'items-center',
        'justify-center',
        'focus:outline-none',
        'focus:shadow-outline',
        'text-center',
        'text-right',
        'text-{fontSize}',
        'underline',
        'font-{fontWeight}',
        'font-{fontFamily}',
        'grid',
        'grid-cols-{gridTemplateColumns}',
        'grid-rows-{gridTemplateRows}',
        'gap-{gap}',
        'flex',
        'flex-row',
        'flex-col',
        'flex-wrap',
        'flex-{flex}',
        'basis-{flexBasis}',
        'leading-{lineHeight}',
        'shadow-{boxShadow}',
        'list-{listStyleType}',
        'list-inside',
        'm-{margin}',
        'mt-{margin}',
        'mb-{margin}',
        'mx-{margin}',
        'my-{margin}',
        'ml-{margin}',
        'mr-{margin}',

        'p-{padding}',
        'pt-{padding}',
        'pb-{padding}',
        'px-{padding}',
        'py-{padding}',
        'pl-{padding}',
        'pr-{padding}',

        'h-{height}',
        'max-h-{maxHeight}',
        'w-{width}',
        'max-w-{maxWidth}',

        /*
        '{flexGrow}',
        '{flexShrink}',
        '{flexFamily}',
        */
        'rounded-{borderRadius}',
        'border',
        'border-{borderWidth}',
        'border-{borderColor}',
        'bg-{backgroundColor}',
        'text-{colors}',
        'hover:bg-{backgroundColor}',
        'hover:text-{colors}',
      ],
    }),
  ],
}
