import {
  HiAcademicCap,
  HiAdjustments,
  HiAnnotation,
  HiArchive,
  HiArrowCircleDown,
  HiArrowCircleLeft,
  HiArrowCircleRight,
  HiArrowCircleUp,
  HiArrowDown,
  HiArrowLeft,
  HiArrowNarrowDown,
  HiArrowNarrowLeft,
  HiArrowNarrowRight,
  HiArrowNarrowUp,
  HiArrowRight,
  HiArrowSmDown,
  HiArrowSmLeft,
  HiArrowSmRight,
  HiArrowSmUp,
  HiArrowUp,
  HiArrowsExpand,
  HiAtSymbol,
  HiBackspace,
  HiBadgeCheck,
  HiBan,
  HiBeaker,
  HiBell,
  HiBookOpen,
  HiBookmarkAlt,
  HiBookmark,
  HiBriefcase,
  HiCake,
  HiCalculator,
  HiCalendar,
  HiCamera,
  HiCash,
  HiChartBar,
  HiChartPie,
  HiChartSquareBar,
  HiChatAlt2,
  HiChatAlt,
  HiChat,
  HiCheckCircle,
  HiCheck,
  HiChevronDoubleDown,
  HiChevronDoubleLeft,
  HiChevronDoubleRight,
  HiChevronDoubleUp,
  HiChevronDown,
  HiChevronLeft,
  HiChevronRight,
  HiChevronUp,
  HiChip,
  HiClipboardCheck,
  HiClipboardCopy,
  HiClipboardList,
  HiClipboard,
  HiClock,
  HiCloudDownload,
  HiCloudUpload,
  HiCloud,
  HiCode,
  HiCog,
  HiCollection,
  HiColorSwatch,
  HiCreditCard,
  HiCubeTransparent,
  HiCube,
  HiCurrencyBangladeshi,
  HiCurrencyDollar,
  HiCurrencyEuro,
  HiCurrencyPound,
  HiCurrencyRupee,
  HiCurrencyYen,
  HiCursorClick,
  HiDatabase,
  HiDesktopComputer,
  HiDeviceMobile,
  HiDeviceTablet,
  HiDocumentAdd,
  HiDocumentDownload,
  HiDocumentDuplicate,
  HiDocumentRemove,
  HiDocumentReport,
  HiDocumentSearch,
  HiDocumentText,
  HiDocument,
  HiDotsCircleHorizontal,
  HiDotsHorizontal,
  HiDotsVertical,
  HiDownload,
  HiDuplicate,
  HiEmojiHappy,
  HiEmojiSad,
  HiExclamationCircle,
  HiExclamation,
  HiExternalLink,
  HiEyeOff,
  HiEye,
  HiFastForward,
  HiFilm,
  HiFilter,
  HiFingerPrint,
  HiFire,
  HiFlag,
  HiFolderAdd,
  HiFolderDownload,
  HiFolderOpen,
  HiFolderRemove,
  HiFolder,
  HiGift,
  HiGlobeAlt,
  HiGlobe,
  HiHand,
  HiHashtag,
  HiHeart,
  HiHome,
  HiIdentification,
  HiInboxIn,
  HiInbox,
  HiInformationCircle,
  HiKey,
  HiLibrary,
  HiLightBulb,
  HiLightningBolt,
  HiLink,
  HiLocationMarker,
  HiLockClosed,
  HiLockOpen,
  HiLogin,
  HiLogout,
  HiMailOpen,
  HiMail,
  HiMap,
  HiMenuAlt1,
  HiMenuAlt2,
  HiMenuAlt3,
  HiMenuAlt4,
  HiMenu,
  HiMicrophone,
  HiMinusCircle,
  HiMinusSm,
  HiMinus,
  HiMoon,
  HiMusicNote,
  HiNewspaper,
  HiOfficeBuilding,
  HiPaperAirplane,
  HiPaperClip,
  HiPause,
  HiPencilAlt,
  HiPencil,
  HiPhoneIncoming,
  HiPhoneMissedCall,
  HiPhoneOutgoing,
  HiPhone,
  HiPhotograph,
  HiPlay,
  HiPlusCircle,
  HiPlusSm,
  HiPlus,
  HiPresentationChartBar,
  HiPresentationChartLine,
  HiPrinter,
  HiPuzzle,
  HiQrcode,
  HiQuestionMarkCircle,
  HiReceiptRefund,
  HiReceiptTax,
  HiRefresh,
  HiReply,
  HiRewind,
  HiRss,
  HiSaveAs,
  HiSave,
  HiScale,
  HiScissors,
  HiSearchCircle,
  HiSearch,
  HiSelector,
  HiServer,
  HiShare,
  HiShieldCheck,
  HiShieldExclamation,
  HiShoppingBag,
  HiShoppingCart,
  HiSortAscending,
  HiSortDescending,
  HiSparkles,
  HiSpeakerphone,
  HiStar,
  HiStatusOffline,
  HiStatusOnline,
  HiStop,
  HiSun,
  HiSupport,
  HiSwitchHorizontal,
  HiSwitchVertical,
  HiTable,
  HiTag,
  HiTemplate,
  HiTerminal,
  HiThumbDown,
  HiThumbUp,
  HiTicket,
  HiTranslate,
  HiTrash,
  HiTrendingDown,
  HiTrendingUp,
  HiTruck,
  HiUpload,
  HiUserAdd,
  HiUserCircle,
  HiUserGroup,
  HiUserRemove,
  HiUser,
  HiUsers,
  HiVariable,
  HiVideoCamera,
  HiViewBoards,
  HiViewGridAdd,
  HiViewGrid,
  HiViewList,
  HiVolumeOff,
  HiVolumeUp,
  HiWifi,
  HiXCircle,
  HiX,
  HiZoomIn,
  HiZoomOut,
  HiOutlineAcademicCap,
  HiOutlineAdjustments,
  HiOutlineAnnotation,
  HiOutlineArchive,
  HiOutlineArrowCircleDown,
  HiOutlineArrowCircleLeft,
  HiOutlineArrowCircleRight,
  HiOutlineArrowCircleUp,
  HiOutlineArrowDown,
  HiOutlineArrowLeft,
  HiOutlineArrowNarrowDown,
  HiOutlineArrowNarrowLeft,
  HiOutlineArrowNarrowRight,
  HiOutlineArrowNarrowUp,
  HiOutlineArrowRight,
  HiOutlineArrowSmDown,
  HiOutlineArrowSmLeft,
  HiOutlineArrowSmRight,
  HiOutlineArrowSmUp,
  HiOutlineArrowUp,
  HiOutlineArrowsExpand,
  HiOutlineAtSymbol,
  HiOutlineBackspace,
  HiOutlineBadgeCheck,
  HiOutlineBan,
  HiOutlineBeaker,
  HiOutlineBell,
  HiOutlineBookOpen,
  HiOutlineBookmarkAlt,
  HiOutlineBookmark,
  HiOutlineBriefcase,
  HiOutlineCake,
  HiOutlineCalculator,
  HiOutlineCalendar,
  HiOutlineCamera,
  HiOutlineCash,
  HiOutlineChartBar,
  HiOutlineChartPie,
  HiOutlineChartSquareBar,
  HiOutlineChatAlt2,
  HiOutlineChatAlt,
  HiOutlineChat,
  HiOutlineCheckCircle,
  HiOutlineCheck,
  HiOutlineChevronDoubleDown,
  HiOutlineChevronDoubleLeft,
  HiOutlineChevronDoubleRight,
  HiOutlineChevronDoubleUp,
  HiOutlineChevronDown,
  HiOutlineChevronLeft,
  HiOutlineChevronRight,
  HiOutlineChevronUp,
  HiOutlineChip,
  HiOutlineClipboardCheck,
  HiOutlineClipboardCopy,
  HiOutlineClipboardList,
  HiOutlineClipboard,
  HiOutlineClock,
  HiOutlineCloudDownload,
  HiOutlineCloudUpload,
  HiOutlineCloud,
  HiOutlineCode,
  HiOutlineCog,
  HiOutlineCollection,
  HiOutlineColorSwatch,
  HiOutlineCreditCard,
  HiOutlineCubeTransparent,
  HiOutlineCube,
  HiOutlineCurrencyBangladeshi,
  HiOutlineCurrencyDollar,
  HiOutlineCurrencyEuro,
  HiOutlineCurrencyPound,
  HiOutlineCurrencyRupee,
  HiOutlineCurrencyYen,
  HiOutlineCursorClick,
  HiOutlineDatabase,
  HiOutlineDesktopComputer,
  HiOutlineDeviceMobile,
  HiOutlineDeviceTablet,
  HiOutlineDocumentAdd,
  HiOutlineDocumentDownload,
  HiOutlineDocumentDuplicate,
  HiOutlineDocumentRemove,
  HiOutlineDocumentReport,
  HiOutlineDocumentSearch,
  HiOutlineDocumentText,
  HiOutlineDocument,
  HiOutlineDotsCircleHorizontal,
  HiOutlineDotsHorizontal,
  HiOutlineDotsVertical,
  HiOutlineDownload,
  HiOutlineDuplicate,
  HiOutlineEmojiHappy,
  HiOutlineEmojiSad,
  HiOutlineExclamationCircle,
  HiOutlineExclamation,
  HiOutlineExternalLink,
  HiOutlineEyeOff,
  HiOutlineEye,
  HiOutlineFastForward,
  HiOutlineFilm,
  HiOutlineFilter,
  HiOutlineFingerPrint,
  HiOutlineFire,
  HiOutlineFlag,
  HiOutlineFolderAdd,
  HiOutlineFolderDownload,
  HiOutlineFolderOpen,
  HiOutlineFolderRemove,
  HiOutlineFolder,
  HiOutlineGift,
  HiOutlineGlobeAlt,
  HiOutlineGlobe,
  HiOutlineHand,
  HiOutlineHashtag,
  HiOutlineHeart,
  HiOutlineHome,
  HiOutlineIdentification,
  HiOutlineInboxIn,
  HiOutlineInbox,
  HiOutlineInformationCircle,
  HiOutlineKey,
  HiOutlineLibrary,
  HiOutlineLightBulb,
  HiOutlineLightningBolt,
  HiOutlineLink,
  HiOutlineLocationMarker,
  HiOutlineLockClosed,
  HiOutlineLockOpen,
  HiOutlineLogin,
  HiOutlineLogout,
  HiOutlineMailOpen,
  HiOutlineMail,
  HiOutlineMap,
  HiOutlineMenuAlt1,
  HiOutlineMenuAlt2,
  HiOutlineMenuAlt3,
  HiOutlineMenuAlt4,
  HiOutlineMenu,
  HiOutlineMicrophone,
  HiOutlineMinusCircle,
  HiOutlineMinusSm,
  HiOutlineMinus,
  HiOutlineMoon,
  HiOutlineMusicNote,
  HiOutlineNewspaper,
  HiOutlineOfficeBuilding,
  HiOutlinePaperAirplane,
  HiOutlinePaperClip,
  HiOutlinePause,
  HiOutlinePencilAlt,
  HiOutlinePencil,
  HiOutlinePhoneIncoming,
  HiOutlinePhoneMissedCall,
  HiOutlinePhoneOutgoing,
  HiOutlinePhone,
  HiOutlinePhotograph,
  HiOutlinePlay,
  HiOutlinePlusCircle,
  HiOutlinePlusSm,
  HiOutlinePlus,
  HiOutlinePresentationChartBar,
  HiOutlinePresentationChartLine,
  HiOutlinePrinter,
  HiOutlinePuzzle,
  HiOutlineQrcode,
  HiOutlineQuestionMarkCircle,
  HiOutlineReceiptRefund,
  HiOutlineReceiptTax,
  HiOutlineRefresh,
  HiOutlineReply,
  HiOutlineRewind,
  HiOutlineRss,
  HiOutlineSaveAs,
  HiOutlineSave,
  HiOutlineScale,
  HiOutlineScissors,
  HiOutlineSearchCircle,
  HiOutlineSearch,
  HiOutlineSelector,
  HiOutlineServer,
  HiOutlineShare,
  HiOutlineShieldCheck,
  HiOutlineShieldExclamation,
  HiOutlineShoppingBag,
  HiOutlineShoppingCart,
  HiOutlineSortAscending,
  HiOutlineSortDescending,
  HiOutlineSparkles,
  HiOutlineSpeakerphone,
  HiOutlineStar,
  HiOutlineStatusOffline,
  HiOutlineStatusOnline,
  HiOutlineStop,
  HiOutlineSun,
  HiOutlineSupport,
  HiOutlineSwitchHorizontal,
  HiOutlineSwitchVertical,
  HiOutlineTable,
  HiOutlineTag,
  HiOutlineTemplate,
  HiOutlineTerminal,
  HiOutlineThumbDown,
  HiOutlineThumbUp,
  HiOutlineTicket,
  HiOutlineTranslate,
  HiOutlineTrash,
  HiOutlineTrendingDown,
  HiOutlineTrendingUp,
  HiOutlineTruck,
  HiOutlineUpload,
  HiOutlineUserAdd,
  HiOutlineUserCircle,
  HiOutlineUserGroup,
  HiOutlineUserRemove,
  HiOutlineUser,
  HiOutlineUsers,
  HiOutlineVariable,
  HiOutlineVideoCamera,
  HiOutlineViewBoards,
  HiOutlineViewGridAdd,
  HiOutlineViewGrid,
  HiOutlineViewList,
  HiOutlineVolumeOff,
  HiOutlineVolumeUp,
  HiOutlineWifi,
  HiOutlineXCircle,
  HiOutlineX,
  HiOutlineZoomIn,
  HiOutlineZoomOut,
} from 'react-icons/hi'
import { type IconType } from 'react-icons/lib'
import Fuse from 'fuse.js'

const icons: Record<string, IconType> = {
  'academic cap': HiAcademicCap,
  adjustments: HiAdjustments,
  annotation: HiAnnotation,
  archive: HiArchive,
  'arrow circle down': HiArrowCircleDown,
  'arrow circle left': HiArrowCircleLeft,
  'arrow circle right': HiArrowCircleRight,
  'arrow circle up': HiArrowCircleUp,
  'arrow down': HiArrowDown,
  'arrow left': HiArrowLeft,
  'arrow narrow down': HiArrowNarrowDown,
  'arrow narrow left': HiArrowNarrowLeft,
  'arrow narrow right': HiArrowNarrowRight,
  'arrow narrow up': HiArrowNarrowUp,
  'arrow right': HiArrowRight,
  'arrow sm down': HiArrowSmDown,
  'arrow sm left': HiArrowSmLeft,
  'arrow sm right': HiArrowSmRight,
  'arrow sm up': HiArrowSmUp,
  'arrow up': HiArrowUp,
  'arrows expand': HiArrowsExpand,
  'at symbol': HiAtSymbol,
  backspace: HiBackspace,
  'badge check': HiBadgeCheck,
  ban: HiBan,
  beaker: HiBeaker,
  bell: HiBell,
  'book open': HiBookOpen,
  'bookmark alt': HiBookmarkAlt,
  bookmark: HiBookmark,
  briefcase: HiBriefcase,
  cake: HiCake,
  calculator: HiCalculator,
  calendar: HiCalendar,
  camera: HiCamera,
  cash: HiCash,
  'chart bar': HiChartBar,
  'chart pie': HiChartPie,
  'chart square bar': HiChartSquareBar,
  'chat alt 2': HiChatAlt2,
  'chat alt': HiChatAlt,
  chat: HiChat,
  'check circle': HiCheckCircle,
  check: HiCheck,
  'chevron double down': HiChevronDoubleDown,
  'chevron double left': HiChevronDoubleLeft,
  'chevron double right': HiChevronDoubleRight,
  'chevron double up': HiChevronDoubleUp,
  'chevron down': HiChevronDown,
  'chevron left': HiChevronLeft,
  'chevron right': HiChevronRight,
  'chevron up': HiChevronUp,
  chip: HiChip,
  'clipboard check': HiClipboardCheck,
  'clipboard copy': HiClipboardCopy,
  'clipboard list': HiClipboardList,
  clipboard: HiClipboard,
  clock: HiClock,
  'cloud download': HiCloudDownload,
  'cloud upload': HiCloudUpload,
  cloud: HiCloud,
  code: HiCode,
  cog: HiCog,
  collection: HiCollection,
  'color swatch': HiColorSwatch,
  'credit card': HiCreditCard,
  'cube transparent': HiCubeTransparent,
  cube: HiCube,
  'currency bangladeshi': HiCurrencyBangladeshi,
  'currency dollar': HiCurrencyDollar,
  'currency euro': HiCurrencyEuro,
  'currency pound': HiCurrencyPound,
  'currency rupee': HiCurrencyRupee,
  'currency yen': HiCurrencyYen,
  'cursor click': HiCursorClick,
  database: HiDatabase,
  'desktop computer': HiDesktopComputer,
  'device mobile': HiDeviceMobile,
  'device tablet': HiDeviceTablet,
  'document add': HiDocumentAdd,
  'document download': HiDocumentDownload,
  'document duplicate': HiDocumentDuplicate,
  'document remove': HiDocumentRemove,
  'document report': HiDocumentReport,
  'document search': HiDocumentSearch,
  'document text': HiDocumentText,
  document: HiDocument,
  'dots circle horizontal': HiDotsCircleHorizontal,
  'dots horizontal': HiDotsHorizontal,
  'dots vertical': HiDotsVertical,
  download: HiDownload,
  duplicate: HiDuplicate,
  'emoji happy': HiEmojiHappy,
  'emoji sad': HiEmojiSad,
  'exclamation circle': HiExclamationCircle,
  exclamation: HiExclamation,
  'external link': HiExternalLink,
  'eye off': HiEyeOff,
  eye: HiEye,
  'fast forward': HiFastForward,
  film: HiFilm,
  filter: HiFilter,
  'finger print': HiFingerPrint,
  fire: HiFire,
  flag: HiFlag,
  'folder add': HiFolderAdd,
  'folder download': HiFolderDownload,
  'folder open': HiFolderOpen,
  'folder remove': HiFolderRemove,
  folder: HiFolder,
  gift: HiGift,
  'globe alt': HiGlobeAlt,
  globe: HiGlobe,
  hand: HiHand,
  hashtag: HiHashtag,
  heart: HiHeart,
  home: HiHome,
  identification: HiIdentification,
  'inbox in': HiInboxIn,
  inbox: HiInbox,
  'information circle': HiInformationCircle,
  key: HiKey,
  library: HiLibrary,
  'light bulb': HiLightBulb,
  'lightning bolt': HiLightningBolt,
  link: HiLink,
  'location marker': HiLocationMarker,
  'lock closed': HiLockClosed,
  'lock open': HiLockOpen,
  login: HiLogin,
  logout: HiLogout,
  'mail open': HiMailOpen,
  mail: HiMail,
  map: HiMap,
  'menu alt 1': HiMenuAlt1,
  'menu alt 2': HiMenuAlt2,
  'menu alt 3': HiMenuAlt3,
  'menu alt 4': HiMenuAlt4,
  menu: HiMenu,
  microphone: HiMicrophone,
  'minus circle': HiMinusCircle,
  'minus sm': HiMinusSm,
  minus: HiMinus,
  moon: HiMoon,
  'music note': HiMusicNote,
  newspaper: HiNewspaper,
  'office building': HiOfficeBuilding,
  'paper airplane': HiPaperAirplane,
  'paper clip': HiPaperClip,
  pause: HiPause,
  'pencil alt': HiPencilAlt,
  pencil: HiPencil,
  'phone incoming': HiPhoneIncoming,
  'phone missed call': HiPhoneMissedCall,
  'phone outgoing': HiPhoneOutgoing,
  phone: HiPhone,
  photograph: HiPhotograph,
  play: HiPlay,
  'plus circle': HiPlusCircle,
  'plus sm': HiPlusSm,
  plus: HiPlus,
  'presentation chart bar': HiPresentationChartBar,
  'presentation chart line': HiPresentationChartLine,
  printer: HiPrinter,
  puzzle: HiPuzzle,
  qrcode: HiQrcode,
  'question mark circle': HiQuestionMarkCircle,
  'receipt refund': HiReceiptRefund,
  'receipt tax': HiReceiptTax,
  refresh: HiRefresh,
  reply: HiReply,
  rewind: HiRewind,
  rss: HiRss,
  'save as': HiSaveAs,
  save: HiSave,
  scale: HiScale,
  scissors: HiScissors,
  'search circle': HiSearchCircle,
  search: HiSearch,
  selector: HiSelector,
  server: HiServer,
  share: HiShare,
  'shield check': HiShieldCheck,
  'shield exclamation': HiShieldExclamation,
  'shopping bag': HiShoppingBag,
  'shopping cart': HiShoppingCart,
  'sort ascending': HiSortAscending,
  'sort descending': HiSortDescending,
  sparkles: HiSparkles,
  speakerphone: HiSpeakerphone,
  star: HiStar,
  'status offline': HiStatusOffline,
  'status online': HiStatusOnline,
  stop: HiStop,
  sun: HiSun,
  support: HiSupport,
  'switch horizontal': HiSwitchHorizontal,
  'switch vertical': HiSwitchVertical,
  table: HiTable,
  tag: HiTag,
  template: HiTemplate,
  terminal: HiTerminal,
  'thumb down': HiThumbDown,
  'thumb up': HiThumbUp,
  ticket: HiTicket,
  translate: HiTranslate,
  trash: HiTrash,
  'trending down': HiTrendingDown,
  'trending up': HiTrendingUp,
  truck: HiTruck,
  upload: HiUpload,
  'user add': HiUserAdd,
  'user circle': HiUserCircle,
  'user group': HiUserGroup,
  'user remove': HiUserRemove,
  user: HiUser,
  users: HiUsers,
  variable: HiVariable,
  'video camera': HiVideoCamera,
  'view boards': HiViewBoards,
  'view grid add': HiViewGridAdd,
  'view grid': HiViewGrid,
  'view list': HiViewList,
  'volume off': HiVolumeOff,
  'volume up': HiVolumeUp,
  wifi: HiWifi,
  'x circle': HiXCircle,
  x: HiX,
  'zoom in': HiZoomIn,
  'zoom out': HiZoomOut,
  'outline academic cap': HiOutlineAcademicCap,
  'outline adjustments': HiOutlineAdjustments,
  'outline annotation': HiOutlineAnnotation,
  'outline archive': HiOutlineArchive,
  'outline arrow circle down': HiOutlineArrowCircleDown,
  'outline arrow circle left': HiOutlineArrowCircleLeft,
  'outline arrow circle right': HiOutlineArrowCircleRight,
  'outline arrow circle up': HiOutlineArrowCircleUp,
  'outline arrow down': HiOutlineArrowDown,
  'outline arrow left': HiOutlineArrowLeft,
  'outline arrow narrow down': HiOutlineArrowNarrowDown,
  'outline arrow narrow left': HiOutlineArrowNarrowLeft,
  'outline arrow narrow right': HiOutlineArrowNarrowRight,
  'outline arrow narrow up': HiOutlineArrowNarrowUp,
  'outline arrow right': HiOutlineArrowRight,
  'outline arrow sm down': HiOutlineArrowSmDown,
  'outline arrow sm left': HiOutlineArrowSmLeft,
  'outline arrow sm right': HiOutlineArrowSmRight,
  'outline arrow sm up': HiOutlineArrowSmUp,
  'outline arrow up': HiOutlineArrowUp,
  'outline arrows expand': HiOutlineArrowsExpand,
  'outline at symbol': HiOutlineAtSymbol,
  'outline backspace': HiOutlineBackspace,
  'outline badge check': HiOutlineBadgeCheck,
  'outline ban': HiOutlineBan,
  'outline beaker': HiOutlineBeaker,
  'outline bell': HiOutlineBell,
  'outline book open': HiOutlineBookOpen,
  'outline bookmark alt': HiOutlineBookmarkAlt,
  'outline bookmark': HiOutlineBookmark,
  'outline briefcase': HiOutlineBriefcase,
  'outline cake': HiOutlineCake,
  'outline calculator': HiOutlineCalculator,
  'outline calendar': HiOutlineCalendar,
  'outline camera': HiOutlineCamera,
  'outline cash': HiOutlineCash,
  'outline chart bar': HiOutlineChartBar,
  'outline chart pie': HiOutlineChartPie,
  'outline chart square bar': HiOutlineChartSquareBar,
  'outline chat alt 2': HiOutlineChatAlt2,
  'outline chat alt': HiOutlineChatAlt,
  'outline chat': HiOutlineChat,
  'outline check circle': HiOutlineCheckCircle,
  'outline check': HiOutlineCheck,
  'outline chevron double down': HiOutlineChevronDoubleDown,
  'outline chevron double left': HiOutlineChevronDoubleLeft,
  'outline chevron double right': HiOutlineChevronDoubleRight,
  'outline chevron double up': HiOutlineChevronDoubleUp,
  'outline chevron down': HiOutlineChevronDown,
  'outline chevron left': HiOutlineChevronLeft,
  'outline chevron right': HiOutlineChevronRight,
  'outline chevron up': HiOutlineChevronUp,
  'outline chip': HiOutlineChip,
  'outline clipboard check': HiOutlineClipboardCheck,
  'outline clipboard copy': HiOutlineClipboardCopy,
  'outline clipboard list': HiOutlineClipboardList,
  'outline clipboard': HiOutlineClipboard,
  'outline clock': HiOutlineClock,
  'outline cloud download': HiOutlineCloudDownload,
  'outline cloud upload': HiOutlineCloudUpload,
  'outline cloud': HiOutlineCloud,
  'outline code': HiOutlineCode,
  'outline cog': HiOutlineCog,
  'outline collection': HiOutlineCollection,
  'outline color swatch': HiOutlineColorSwatch,
  'outline credit card': HiOutlineCreditCard,
  'outline cube transparent': HiOutlineCubeTransparent,
  'outline cube': HiOutlineCube,
  'outline currency bangladeshi': HiOutlineCurrencyBangladeshi,
  'outline currency dollar': HiOutlineCurrencyDollar,
  'outline currency euro': HiOutlineCurrencyEuro,
  'outline currency pound': HiOutlineCurrencyPound,
  'outline currency rupee': HiOutlineCurrencyRupee,
  'outline currency yen': HiOutlineCurrencyYen,
  'outline cursor click': HiOutlineCursorClick,
  'outline database': HiOutlineDatabase,
  'outline desktop computer': HiOutlineDesktopComputer,
  'outline device mobile': HiOutlineDeviceMobile,
  'outline device tablet': HiOutlineDeviceTablet,
  'outline document add': HiOutlineDocumentAdd,
  'outline document download': HiOutlineDocumentDownload,
  'outline document duplicate': HiOutlineDocumentDuplicate,
  'outline document remove': HiOutlineDocumentRemove,
  'outline document report': HiOutlineDocumentReport,
  'outline document search': HiOutlineDocumentSearch,
  'outline document text': HiOutlineDocumentText,
  'outline document': HiOutlineDocument,
  'outline dots circle horizontal': HiOutlineDotsCircleHorizontal,
  'outline dots horizontal': HiOutlineDotsHorizontal,
  'outline dots vertical': HiOutlineDotsVertical,
  'outline download': HiOutlineDownload,
  'outline duplicate': HiOutlineDuplicate,
  'outline emoji happy': HiOutlineEmojiHappy,
  'outline emoji sad': HiOutlineEmojiSad,
  'outline exclamation circle': HiOutlineExclamationCircle,
  'outline exclamation': HiOutlineExclamation,
  'outline external link': HiOutlineExternalLink,
  'outline eye off': HiOutlineEyeOff,
  'outline eye': HiOutlineEye,
  'outline fast forward': HiOutlineFastForward,
  'outline film': HiOutlineFilm,
  'outline filter': HiOutlineFilter,
  'outline finger print': HiOutlineFingerPrint,
  'outline fire': HiOutlineFire,
  'outline flag': HiOutlineFlag,
  'outline folder add': HiOutlineFolderAdd,
  'outline folder download': HiOutlineFolderDownload,
  'outline folder open': HiOutlineFolderOpen,
  'outline folder remove': HiOutlineFolderRemove,
  'outline folder': HiOutlineFolder,
  'outline gift': HiOutlineGift,
  'outline globe alt': HiOutlineGlobeAlt,
  'outline globe': HiOutlineGlobe,
  'outline hand': HiOutlineHand,
  'outline hashtag': HiOutlineHashtag,
  'outline heart': HiOutlineHeart,
  'outline home': HiOutlineHome,
  'outline identification': HiOutlineIdentification,
  'outline inbox in': HiOutlineInboxIn,
  'outline inbox': HiOutlineInbox,
  'outline information circle': HiOutlineInformationCircle,
  'outline key': HiOutlineKey,
  'outline library': HiOutlineLibrary,
  'outline light bulb': HiOutlineLightBulb,
  'outline lightning bolt': HiOutlineLightningBolt,
  'outline link': HiOutlineLink,
  'outline location marker': HiOutlineLocationMarker,
  'outline lock closed': HiOutlineLockClosed,
  'outline lock open': HiOutlineLockOpen,
  'outline login': HiOutlineLogin,
  'outline logout': HiOutlineLogout,
  'outline mail open': HiOutlineMailOpen,
  'outline mail': HiOutlineMail,
  'outline map': HiOutlineMap,
  'outline menu alt 1': HiOutlineMenuAlt1,
  'outline menu alt 2': HiOutlineMenuAlt2,
  'outline menu alt 3': HiOutlineMenuAlt3,
  'outline menu alt 4': HiOutlineMenuAlt4,
  'outline menu': HiOutlineMenu,
  'outline microphone': HiOutlineMicrophone,
  'outline minus circle': HiOutlineMinusCircle,
  'outline minus sm': HiOutlineMinusSm,
  'outline minus': HiOutlineMinus,
  'outline moon': HiOutlineMoon,
  'outline music note': HiOutlineMusicNote,
  'outline newspaper': HiOutlineNewspaper,
  'outline office building': HiOutlineOfficeBuilding,
  'outline paper airplane': HiOutlinePaperAirplane,
  'outline paper clip': HiOutlinePaperClip,
  'outline pause': HiOutlinePause,
  'outline pencil alt': HiOutlinePencilAlt,
  'outline pencil': HiOutlinePencil,
  'outline phone incoming': HiOutlinePhoneIncoming,
  'outline phone missed call': HiOutlinePhoneMissedCall,
  'outline phone outgoing': HiOutlinePhoneOutgoing,
  'outline phone': HiOutlinePhone,
  'outline photograph': HiOutlinePhotograph,
  'outline play': HiOutlinePlay,
  'outline plus circle': HiOutlinePlusCircle,
  'outline plus sm': HiOutlinePlusSm,
  'outline plus': HiOutlinePlus,
  'outline presentation chart bar': HiOutlinePresentationChartBar,
  'outline presentation chart line': HiOutlinePresentationChartLine,
  'outline printer': HiOutlinePrinter,
  'outline puzzle': HiOutlinePuzzle,
  'outline qrcode': HiOutlineQrcode,
  'outline question mark circle': HiOutlineQuestionMarkCircle,
  'outline receipt refund': HiOutlineReceiptRefund,
  'outline receipt tax': HiOutlineReceiptTax,
  'outline refresh': HiOutlineRefresh,
  'outline reply': HiOutlineReply,
  'outline rewind': HiOutlineRewind,
  'outline rss': HiOutlineRss,
  'outline save as': HiOutlineSaveAs,
  'outline save': HiOutlineSave,
  'outline scale': HiOutlineScale,
  'outline scissors': HiOutlineScissors,
  'outline search circle': HiOutlineSearchCircle,
  'outline search': HiOutlineSearch,
  'outline selector': HiOutlineSelector,
  'outline server': HiOutlineServer,
  'outline share': HiOutlineShare,
  'outline shield check': HiOutlineShieldCheck,
  'outline shield exclamation': HiOutlineShieldExclamation,
  'outline shopping bag': HiOutlineShoppingBag,
  'outline shopping cart': HiOutlineShoppingCart,
  'outline sort ascending': HiOutlineSortAscending,
  'outline sort descending': HiOutlineSortDescending,
  'outline sparkles': HiOutlineSparkles,
  'outline speakerphone': HiOutlineSpeakerphone,
  'outline star': HiOutlineStar,
  'outline status offline': HiOutlineStatusOffline,
  'outline status online': HiOutlineStatusOnline,
  'outline stop': HiOutlineStop,
  'outline sun': HiOutlineSun,
  'outline support': HiOutlineSupport,
  'outline switch horizontal': HiOutlineSwitchHorizontal,
  'outline switch vertical': HiOutlineSwitchVertical,
  'outline table': HiOutlineTable,
  'outline tag': HiOutlineTag,
  'outline template': HiOutlineTemplate,
  'outline terminal': HiOutlineTerminal,
  'outline thumb down': HiOutlineThumbDown,
  'outline thumb up': HiOutlineThumbUp,
  'outline ticket': HiOutlineTicket,
  'outline translate': HiOutlineTranslate,
  'outline trash': HiOutlineTrash,
  'outline trending down': HiOutlineTrendingDown,
  'outline trending up': HiOutlineTrendingUp,
  'outline truck': HiOutlineTruck,
  'outline upload': HiOutlineUpload,
  'outline user add': HiOutlineUserAdd,
  'outline user circle': HiOutlineUserCircle,
  'outline user group': HiOutlineUserGroup,
  'outline user remove': HiOutlineUserRemove,
  'outline user': HiOutlineUser,
  'outline users': HiOutlineUsers,
  'outline variable': HiOutlineVariable,
  'outline video camera': HiOutlineVideoCamera,
  'outline view boards': HiOutlineViewBoards,
  'outline view grid add': HiOutlineViewGridAdd,
  'outline view grid': HiOutlineViewGrid,
  'outline view list': HiOutlineViewList,
  'outline volume off': HiOutlineVolumeOff,
  'outline volume up': HiOutlineVolumeUp,
  'outline wifi': HiOutlineWifi,
  'outline x circle': HiOutlineXCircle,
  'outline x': HiOutlineX,
  'outline zoom in': HiOutlineZoomIn,
  'outline zoom out': HiOutlineZoomOut,
}

export const index = new Fuse(
  Object.entries(icons).map(([name, component]) => ({
    name,
    component,
  })),
  {
    keys: ['name'],
    findAllMatches: true,
    isCaseSensitive: false,
    threshold: 1.0,
  }
)

export const getIcon = (icon?: string): IconType => {
  if (!icon) {
    return null
  }

  const best = index.search(icon)[0]
  if (!best) {
    return
  }

  return best.item.component
}
