export const sample = [
  `⓪ui.theme߷primaryText=#000000߷secondaryText=#666666߷foreground=#ffffff߷background=#cccccc߷accent=#ff0000`,
  `①ui.navbar߷fluid=true߷rounded=true`,
  `②ui.button߷Home`,
  `②ui.button߷About`,
  `①ui.p߷Welcome to my blog! On this site you will\nknow everything about my dog life. Woof, woof!`,
  `⓪pdf`,
  `①pdf.h1߷The Test`,
  `①pdf.author߷Anonymous Developer`,
  `①pdf.h3߷Hello`,
  `①pdf.p߷Hello. This is a test.`,
  `①pdf.h3߷World`,
  `①pdf.p߷Hello, World!`,
  `⓪ui.h1߷Mouse tracking app`,
  `⓪ui.p߷Mouse cursor is at: $mouse.x and $mouse.y`,
  `⓪music.song߷isPlaying=true`,
  `①music.track߷steps=[['C3','E3','G3'],['G3','B4','D4']]`,
  `②music.instrument߷type=synth`,
  `⓪eval߷$a = $mouse.clicked ? 2 : 1`,
  `⓪eval߷$b = '#ffffff'`,
  `⓪ui.h2߷3D App Demo`,
  `①fiber.scene`,
  `②fiber.ball߷size=$a * 1.5߷color=$mouse.clicked ? $b : '#ff0000'`,
  `②fiber.ball߷size=$a * 2.5߷color=$mouse.clicked ? $b : '#00ff00'`,
  `②fiber.ball߷size=$b * 3.5߷color=$mouse.clicked ? $b : '#0000ff'`,
].join('')
